/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bookstore_ms;


import java.awt.HeadlessException;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author USER
 */
public class JF_BillingCus extends javax.swing.JFrame {

    /**
     * Creates new form JF_asdasda
     */
    public JF_BillingCus() {
        JOptionPane.showMessageDialog(this, "You must to login to use!");
        new JF_Login().setVisible(true);
        this.dispose();
    }

    String ussername = "Undefined";
    int iduser = 0;
    public JF_BillingCus(int id){
        initComponents();
        iduser = id;
        DisplayBooks();
        SpinnerNumberModel gioihan = new SpinnerNumberModel(1, 1, Integer.MAX_VALUE, 1);
        quanOrBookTB.setModel(gioihan);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addbillBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        printBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        usernameTB = new javax.swing.JLabel();
        infoCus = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        billing = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        booksTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        codeBookTB = new javax.swing.JTextField();
        nameBookTB = new javax.swing.JTextField();
        priceBookTB = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        quanBookTB1 = new javax.swing.JTextField();
        quantityBookTB = new javax.swing.JLabel();
        quanLeftBookTB = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        quanOrBookTB = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        discountCusTB = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        typeCusTB = new javax.swing.JTextField();
        nameCusTB = new javax.swing.JTextField();
        Save = new javax.swing.JButton();
        panelnvoice = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookBillsTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cusNameLB = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        phoneBill = new javax.swing.JLabel();
        staffbill = new javax.swing.JLabel();
        idTimeBills = new javax.swing.JLabel();
        addressBill = new javax.swing.JLabel();
        typeCbill = new javax.swing.JLabel();
        subtotalLB = new javax.swing.JLabel();
        discountLB = new javax.swing.JLabel();
        totalPaymentLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(229, 229, 229));
        jPanel1.setForeground(new java.awt.Color(128, 128, 128));

        addbillBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        addbillBtn.setForeground(new java.awt.Color(32, 215, 195));
        addbillBtn.setText("Add to bill");
        addbillBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbillBtnActionPerformed(evt);
            }
        });

        resetBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        resetBtn.setForeground(new java.awt.Color(32, 215, 195));
        resetBtn.setText("Reset");
        resetBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetBtnMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(32, 215, 195));
        jLabel9.setText("Book List");

        printBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        printBtn.setForeground(new java.awt.Color(32, 215, 195));
        printBtn.setText("Print");
        printBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printBtnMouseClicked(evt);
            }
        });
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });

        logoutBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(32, 215, 195));
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookstore_ms/Images/power.png"))); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
        });
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel21.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(32, 215, 195));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Book Store Software");

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookstore_ms/Images/close-button.png"))); // NOI18N
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookstore_ms/Images/info.png"))); // NOI18N

        usernameTB.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        usernameTB.setForeground(new java.awt.Color(32, 215, 195));
        usernameTB.setText("Username");
        usernameTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameTBMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameTB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177)
                .addComponent(jLabel22)
                .addGap(18, 18, 18))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(usernameTB)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        infoCus.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        infoCus.setForeground(new java.awt.Color(32, 215, 195));
        infoCus.setText("Info");
        infoCus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoCusMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookstore_ms/Images/user.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookstore_ms/Images/billing.png"))); // NOI18N

        billing.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        billing.setForeground(new java.awt.Color(0, 100, 101));
        billing.setText("Billing");
        billing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billingMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(32, 215, 195));
        jPanel2.setPreferredSize(new java.awt.Dimension(55, 3));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        booksTable.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        booksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Author", "Categories", "Publisher", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        booksTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        booksTable.setGridColor(new java.awt.Color(204, 204, 204));
        booksTable.setName(""); // NOI18N
        booksTable.setRequestFocusEnabled(false);
        booksTable.setRowHeight(30);
        booksTable.setRowMargin(5);
        booksTable.setSelectionBackground(new java.awt.Color(32, 215, 195));
        booksTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        booksTable.setShowGrid(true);
        booksTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                booksTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(booksTable);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Info book", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bookman Old Style", 1, 16), new java.awt.Color(0, 153, 153))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setToolTipText("");
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        codeBookTB.setEditable(false);
        codeBookTB.setBackground(new java.awt.Color(255, 255, 255));
        codeBookTB.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        codeBookTB.setToolTipText("");
        codeBookTB.setBorder(null);
        codeBookTB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        codeBookTB.setFocusable(false);
        codeBookTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeBookTBActionPerformed(evt);
            }
        });

        nameBookTB.setEditable(false);
        nameBookTB.setBackground(new java.awt.Color(255, 255, 255));
        nameBookTB.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        nameBookTB.setToolTipText("");
        nameBookTB.setBorder(null);
        nameBookTB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nameBookTB.setFocusable(false);
        nameBookTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameBookTBActionPerformed(evt);
            }
        });

        priceBookTB.setEditable(false);
        priceBookTB.setBackground(new java.awt.Color(255, 255, 255));
        priceBookTB.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        priceBookTB.setToolTipText("");
        priceBookTB.setBorder(null);
        priceBookTB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        priceBookTB.setFocusable(false);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(32, 215, 195));
        jLabel10.setText("Book code:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(32, 215, 195));
        jLabel3.setText("Book name:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(32, 215, 195));
        jLabel5.setText("Price:");

        quanBookTB1.setEditable(false);
        quanBookTB1.setBackground(new java.awt.Color(255, 255, 255));
        quanBookTB1.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        quanBookTB1.setToolTipText("");
        quanBookTB1.setBorder(null);
        quanBookTB1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quanBookTB1.setFocusable(false);
        quanBookTB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanBookTB1ActionPerformed(evt);
            }
        });

        quantityBookTB.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        quantityBookTB.setForeground(new java.awt.Color(32, 215, 195));
        quantityBookTB.setText("Quantity:");

        quanLeftBookTB.setEditable(false);
        quanLeftBookTB.setBackground(new java.awt.Color(255, 255, 255));
        quanLeftBookTB.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        quanLeftBookTB.setForeground(new java.awt.Color(255, 255, 255));
        quanLeftBookTB.setText("0");
        quanLeftBookTB.setToolTipText("");
        quanLeftBookTB.setBorder(null);
        quanLeftBookTB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quanLeftBookTB.setFocusable(false);
        quanLeftBookTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLeftBookTBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(quantityBookTB))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codeBookTB, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(nameBookTB)
                                .addGap(6, 6, 6))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(quanBookTB1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(quanLeftBookTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(priceBookTB, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addComponent(codeBookTB, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nameBookTB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantityBookTB)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(priceBookTB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quanBookTB1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quanLeftBookTB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Info order", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bookman Old Style", 1, 16), new java.awt.Color(0, 153, 153))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(32, 215, 195));
        jLabel6.setText("Quantity");

        quanOrBookTB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        quanOrBookTB.setEditor(new javax.swing.JSpinner.NumberEditor(quanOrBookTB, ""));
        quanOrBookTB.setFocusTraversalPolicyProvider(true);
        quanOrBookTB.setValue(1);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(32, 215, 195));
        jLabel4.setText("Customer");

        discountCusTB.setEditable(false);
        discountCusTB.setBackground(new java.awt.Color(255, 255, 255));
        discountCusTB.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        discountCusTB.setBorder(null);
        discountCusTB.setFocusable(false);
        discountCusTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountCusTBActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(32, 215, 195));
        jLabel7.setText("Discount");

        typeCusTB.setEditable(false);
        typeCusTB.setBackground(new java.awt.Color(255, 255, 255));
        typeCusTB.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        typeCusTB.setForeground(new java.awt.Color(255, 255, 255));
        typeCusTB.setBorder(null);
        typeCusTB.setFocusable(false);
        typeCusTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeCusTBActionPerformed(evt);
            }
        });

        nameCusTB.setEditable(false);
        nameCusTB.setBackground(new java.awt.Color(255, 255, 255));
        nameCusTB.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        nameCusTB.setBorder(null);
        nameCusTB.setFocusable(false);
        nameCusTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameCusTBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quanOrBookTB))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(discountCusTB, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(typeCusTB, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 28, Short.MAX_VALUE))
                            .addComponent(nameCusTB))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(quanOrBookTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(nameCusTB, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(discountCusTB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(typeCusTB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Save.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Save.setForeground(new java.awt.Color(32, 215, 195));
        Save.setText("Save");
        Save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveMouseClicked(evt);
            }
        });
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        panelnvoice.setBackground(new java.awt.Color(255, 255, 255));

        bookBillsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "IdBook", "Name", "Quantity", "Price", "Total Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bookBillsTable);
        if (bookBillsTable.getColumnModel().getColumnCount() > 0) {
            bookBillsTable.getColumnModel().getColumn(0).setResizable(false);
            bookBillsTable.getColumnModel().getColumn(0).setPreferredWidth(10);
            bookBillsTable.getColumnModel().getColumn(1).setResizable(false);
            bookBillsTable.getColumnModel().getColumn(1).setPreferredWidth(10);
            bookBillsTable.getColumnModel().getColumn(2).setResizable(false);
            bookBillsTable.getColumnModel().getColumn(3).setResizable(false);
            bookBillsTable.getColumnModel().getColumn(3).setPreferredWidth(10);
            bookBillsTable.getColumnModel().getColumn(4).setResizable(false);
            bookBillsTable.getColumnModel().getColumn(4).setPreferredWidth(10);
            bookBillsTable.getColumnModel().getColumn(5).setResizable(false);
            bookBillsTable.getColumnModel().getColumn(5).setPreferredWidth(20);
        }

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel1.setText("Subtotal: $");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel2.setText("Total Payment: $");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel16.setText("Discount: - $");

        cusNameLB.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cusNameLB.setText("Customer:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Books Bill");

        phoneBill.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        phoneBill.setText("Phone:");

        staffbill.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        staffbill.setText("Staff:");

        idTimeBills.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idTimeBills.setText("ID: 1215312 - 19/12/2023, 10:30PM");
        idTimeBills.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        idTimeBills.setName(""); // NOI18N

        addressBill.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        addressBill.setText("Address:");

        typeCbill.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        typeCbill.setText("Type:");

        subtotalLB.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        subtotalLB.setText("0.0");

        discountLB.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        discountLB.setText("0.0");

        totalPaymentLB.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        totalPaymentLB.setText("0.0");

        javax.swing.GroupLayout panelnvoiceLayout = new javax.swing.GroupLayout(panelnvoice);
        panelnvoice.setLayout(panelnvoiceLayout);
        panelnvoiceLayout.setHorizontalGroup(
            panelnvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(panelnvoiceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelnvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelnvoiceLayout.createSequentialGroup()
                        .addComponent(cusNameLB, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(typeCbill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelnvoiceLayout.createSequentialGroup()
                        .addComponent(staffbill, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(phoneBill, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addressBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(panelnvoiceLayout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addComponent(totalPaymentLB, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelnvoiceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelnvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelnvoiceLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelnvoiceLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, 0)
                        .addComponent(subtotalLB, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelnvoiceLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 0, 0)
                        .addComponent(discountLB, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelnvoiceLayout.createSequentialGroup()
                        .addComponent(idTimeBills, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );
        panelnvoiceLayout.setVerticalGroup(
            panelnvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelnvoiceLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idTimeBills)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelnvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cusNameLB)
                    .addComponent(typeCbill))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addressBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelnvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staffbill)
                    .addComponent(phoneBill))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelnvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(subtotalLB))
                .addGap(5, 5, 5)
                .addGroup(panelnvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(discountLB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelnvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(totalPaymentLB))
                .addGap(15, 15, 15))
        );

        idTimeBills.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1077, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(logoutBtn)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(resetBtn)
                                            .addGap(18, 18, 18)
                                            .addComponent(addbillBtn))
                                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jScrollPane3)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelnvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(printBtn)
                                .addGap(291, 291, 291)
                                .addComponent(Save))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(billing, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoCus, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(infoCus)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billing)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(resetBtn)
                                    .addComponent(addbillBtn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(3, 3, 3)))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(panelnvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(logoutBtn)
                        .addComponent(printBtn))
                    .addComponent(Save, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printBtnActionPerformed

    private void discountCusTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountCusTBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discountCusTBActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void billingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billingMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_billingMouseClicked
    Connection conn = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    int st; //status
    int getquanBookTB = 0;
    private void booksTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booksTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)booksTable.getModel();
        int myIndex = booksTable.getSelectedRow();
        codeBookTB.setText(model.getValueAt(myIndex, 0).toString());
        nameBookTB.setText(model.getValueAt(myIndex, 1).toString());
        priceBookTB.setText(model.getValueAt(myIndex, 6).toString());
        
        int qtyBook = Integer.parseInt(model.getValueAt(myIndex, 5).toString());
        int qtyLeftBook = getQtyOrderBook(qtyBook);
        quanLeftBookTB.setText(String.valueOf(qtyLeftBook));
        quanBookTB1.setText(String.valueOf(qtyBook - qtyLeftBook));
    }//GEN-LAST:event_booksTableMouseClicked

    private void nameBookTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameBookTBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameBookTBActionPerformed

    private void infoCusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoCusMouseClicked
        // TODO add your handling code here:
        new JF_InfoCus(iduser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_infoCusMouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel22MouseClicked

    private void resetBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetBtnMouseClicked
        // TODO add your handling code here:
        ResetBook();
    }//GEN-LAST:event_resetBtnMouseClicked

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        // TODO add your handling code here:
        new JF_Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBtnMouseClicked

    private void printBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printBtnMouseClicked
        // TODO add your handling code here:
        try {
            bookBillsTable.print();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_printBtnMouseClicked

    private void codeBookTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeBookTBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeBookTBActionPerformed

    private void quanBookTB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanBookTB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quanBookTB1ActionPerformed

    private void SaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)bookBillsTable.getModel();
        if(codeBookTB.getText().isEmpty() ||
                nameCusTB.getText().isEmpty()||
                dtm.getRowCount() == 0)
            JOptionPane.showMessageDialog(this, "Missing Infomation!");
        else{
            conn = ConnectionFactory.getConnection();
            try {
                //save orders
                String query1 = "INSERT INTO orders(BillId, CusId, DateCreate, TotalPrice, IsPaid, UId) "
                        + "VALUES (?,?,?,?,?,?)";
                ps = conn.prepareStatement(query1);
                String getIdBill = idTimeBills.getText();
                String billId = getIdBill.substring(4, 13);
                LocalDateTime localDateTime = LocalDateTime.now();
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
                String formattedDateTime = localDateTime.format(formatter);
                ps.setInt(1, Integer.parseInt(billId));
                ps.setInt(2, iduser);
                ps.setString(3, formattedDateTime);
                ps.setFloat(4, Float.parseFloat(totalPaymentLB.getText()));
                ps.setBoolean(5, true);
                ps.setInt(6, -1);
                st = ps.executeUpdate();
                
                //update type cus
                UpdateTypeCus(iduser);
                
                //save detail orders
                
                for(int i = 0; i < dtm.getRowCount();i++){
                    String query2 = "INSERT INTO orderdetails(BillId, BookId, BQuantity, Subtotal) "
                        + "VALUES (?,?,?,?)";
                    ps = conn.prepareStatement(query2);
                    ps.setInt(1, Integer.parseInt(billId));
                    ps.setInt(2, Integer.parseInt(dtm.getValueAt(i, 1).toString()));
                    ps.setInt(3, Integer.parseInt(dtm.getValueAt(i, 3).toString()));
                    ps.setFloat(4, Float.parseFloat(dtm.getValueAt(i, 5).toString()));
                    st = ps.executeUpdate();
                    
                    //update quantity book
                    int qtyBook1 = Integer.parseInt(dtm.getValueAt(i, 3).toString());
                    String query3 = "update books set Quantity = Quantity -" +qtyBook1+ " where BId = " + Integer.parseInt(dtm.getValueAt(i, 1).toString());
                    
                    ps = conn.prepareStatement(query3);
                    st = ps.executeUpdate();
                }
                
                JOptionPane.showMessageDialog(this, "Order saved!");
                ResetBook();
                DisplayBooks();
            } catch (HeadlessException | NumberFormatException | SQLException e) {
                JOptionPane.showMessageDialog(this, "Unexpected exception!");
                st = -2;
            }
        }
        
        
        
        
    }//GEN-LAST:event_SaveMouseClicked

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveActionPerformed

    private int i = 0;
    private void addbillBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbillBtnActionPerformed
        // TODO add your handling code here:
        if(codeBookTB.getText().isEmpty() || nameCusTB.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "Miss Infomation!");
        else{
            int price = Integer.parseInt(priceBookTB.getText());
            int qty = Integer.parseInt(quanOrBookTB.getValue().toString());
            quanOrBookTB.setValue(Math.max(1, qty));
            if (qty < 1) {
                JOptionPane.showMessageDialog(this, "Quantity must higher or equal to 1.", "ERROR", JOptionPane.ERROR_MESSAGE);
                return; 
            }
            // return quantity book after add
            int qtyLeftBook = Integer.parseInt(quanBookTB1.getText()) - qty;
            quanBookTB1.setText(String.valueOf(qtyLeftBook));
            if (qty > Integer.parseInt(quanBookTB1.getText())) {
                JOptionPane.showMessageDialog(this, "Quantity must lower or equal this book's quantity (<=" + quanBookTB1.getText() +")!", "ERROR", JOptionPane.ERROR_MESSAGE);
                return; 
            }
            int total = 0;
            int flag = 0;
            DefaultTableModel dtm = (DefaultTableModel)bookBillsTable.getModel();
            //check idbook existed
            for(int j = 0; j < dtm.getRowCount() && dtm.getRowCount() > 0; j++){
                if(codeBookTB.getText().equals(dtm.getValueAt(j, 1).toString())){
                    int oldQty = Integer.parseInt(dtm.getValueAt(j, 3).toString());
                    qty = qty + oldQty;
                    total = price * qty;
                    dtm.setValueAt(qty, j, 3);
                    dtm.setValueAt(total, j, 5);
                    flag = 1;
                    break;
                }
            }
            if(flag != 1){
                i++;
                total = price * qty;
                dtm.addRow(new Object[]{
                    i,
                    codeBookTB.getText(),
                    nameBookTB.getText(),
                    qty,
                    priceBookTB.getText(),
                    total
                });
            }
        }
        Payment();
        
    }//GEN-LAST:event_addbillBtnActionPerformed

    private void typeCusTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeCusTBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeCusTBActionPerformed

    private void nameCusTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameCusTBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameCusTBActionPerformed

    private void quanLeftBookTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanLeftBookTBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quanLeftBookTBActionPerformed
  
    private void usernameTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameTBMouseClicked
        // TODO add your handling code here:
        new JF_InfoCus(iduser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_usernameTBMouseClicked
  
    private float subtotal = 0;
    private float totalpay = 0;
    private void Payment(){
        subtotal = 0;
        //
        //settext payment
        //get discount
        DefaultTableModel dtm = (DefaultTableModel)bookBillsTable.getModel();
        if(dtm.getRowCount() != 0){
            String getdisc = discountCusTB.getText();
            int disc = 0;
            if(!getdisc.equals("0%")){
                disc = Integer.parseInt(getdisc.substring(0, 2).trim());
            }
            for(int l = 0; l< dtm.getRowCount(); l++){
                int getttPrice = Integer.parseInt(dtm.getValueAt(l, 5).toString());
                subtotal += getttPrice;
            }
            subtotalLB.setText(Float.toString(subtotal));
            float d = (float)disc /100;
            float d2 = subtotal * d;
            discountLB.setText(Float.toString(d2));
            totalpay = subtotal - d2;
            totalPaymentLB.setText(Float.toString(totalpay));
        }
    }
    
    private int getQtyOrderBook(int qtyBook){
        int qtyRelease = 0;
        DefaultTableModel dtm = (DefaultTableModel)bookBillsTable.getModel();
        if(dtm.getRowCount() != 0){
             for(int l = 0; l< dtm.getRowCount(); l++){
                 if(codeBookTB.getText().equals(dtm.getValueAt(l, 1))){
                     qtyRelease = Integer.parseInt(dtm.getValueAt(l, 3).toString());
                     //qtyRelease = qtyBook - qtyRelease;
                 }
            }
        }
        return qtyRelease;
    }
    
    private void UpdateTypeCus(int id){
        String querySelect = "SELECT SUM(o.TotalPrice) as 'TotalPayment'\n" +
                        "from customers c JOIN orders o ON c.CId = o.CusId\n" +
                        "where c.CId =" + id ;
        try {
            ps = conn.prepareStatement(querySelect);
            rs = ps.executeQuery();
            if(rs.next()){
                String queryUpdate = "update customers set TypeCus = ? where CId = " + id;
                ps = conn.prepareStatement(queryUpdate);
                int result = rs.getInt("TotalPayment");
                if(result >= 800 && result < 1500){
                    ps.setInt(1, 2);
                }else if(result >= 1500){
                    ps.setInt(1, 3);
                }else
                    ps.setInt(1, 1);
                st = ps.executeUpdate();
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, "Can't update");
        }
    }
    
    private void DisplayBooks(){
        conn = ConnectionFactory.getConnection();
        try {
            String query = "select * from books";
            ps = conn.prepareStatement(query);
            rs = ps.executeQuery(query);
            booksTable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Unexpected DisplayBooks");
        }
        /// display time id invoice
        Random rand = new Random();
        int randomNumber1 = rand.nextInt(1000000, 1000000000);
        int randomNumber2 = rand.nextInt(10000, 100000);
        LocalDateTime localDateTime = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        String formattedDateTime = localDateTime.format(formatter);
        idTimeBills.setText("ID: " + randomNumber1 + randomNumber2 + ", " + formattedDateTime);
        // Info customer
        conn = ConnectionFactory.getConnection();
        try {
            String query = "SELECT * FROM customers WHERE CId =" + iduser;
            ps = conn.prepareStatement(query);
            rs = ps.executeQuery(query);
            if(rs.next()){
                ussername = rs.getString("CName");
                usernameTB.setText(ussername);
                nameCusTB.setText(ussername);
                //settext cus info
                cusNameLB.setText("Customer: " + ussername);
                addressBill.setText("Address: " + rs.getString("CAddress"));
                phoneBill.setText(("Phone: " + rs.getString("CPhone")));
                staffbill.setText("Staff: null");
                //set type cus
                int idTypeCus = rs.getInt("TypeCus");
                ps = conn.prepareStatement("select * from typecustomers where TypeCId = ?");
                ps.setInt(1, idTypeCus);
                rs = ps.executeQuery();
                if(rs.next()) {
                    String discount = rs.getString("Discount");
                    discountCusTB.setText(discount + "%");
                    typeCusTB.setText(rs.getString("TypeCName"));
                    typeCbill.setText("Type: " + typeCusTB.getText());
                }
            }
                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Unexpected getCusInfo");
        }
    }
    
    private void ResetBook(){
        codeBookTB.setText("");
        nameBookTB.setText("");
        priceBookTB.setText("");
        quanOrBookTB.setValue(1);
        quanBookTB1.setText("");
        DefaultTableModel dtm = (DefaultTableModel)bookBillsTable.getModel();
        dtm.setRowCount(0);
        i = 0;
        subtotalLB.setText("0");
        subtotal = 0;
        discountLB.setText("0");
        totalPaymentLB.setText("0");
        totalpay = 0;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_BillingCus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_BillingCus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_BillingCus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_BillingCus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_BillingCus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Save;
    private javax.swing.JButton addbillBtn;
    private javax.swing.JLabel addressBill;
    private javax.swing.JLabel billing;
    private javax.swing.JTable bookBillsTable;
    private javax.swing.JTable booksTable;
    private javax.swing.JTextField codeBookTB;
    private javax.swing.JLabel cusNameLB;
    private javax.swing.JTextField discountCusTB;
    private javax.swing.JLabel discountLB;
    private javax.swing.JLabel idTimeBills;
    private javax.swing.JLabel infoCus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTextField nameBookTB;
    private javax.swing.JTextField nameCusTB;
    private javax.swing.JPanel panelnvoice;
    private javax.swing.JLabel phoneBill;
    private javax.swing.JTextField priceBookTB;
    private javax.swing.JButton printBtn;
    private javax.swing.JTextField quanBookTB1;
    private javax.swing.JTextField quanLeftBookTB;
    private javax.swing.JSpinner quanOrBookTB;
    private javax.swing.JLabel quantityBookTB;
    private javax.swing.JButton resetBtn;
    private javax.swing.JLabel staffbill;
    private javax.swing.JLabel subtotalLB;
    private javax.swing.JLabel totalPaymentLB;
    private javax.swing.JLabel typeCbill;
    private javax.swing.JTextField typeCusTB;
    private javax.swing.JLabel usernameTB;
    // End of variables declaration//GEN-END:variables
}
