/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bookstore_ms;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Properties;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField.AbstractFormatter;
import javax.swing.JLabel;
import javax.swing.text.DateFormatter;
import org.jdatepicker.impl.DateComponentFormatter;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author USER
 */
public class JF_SellReport extends javax.swing.JFrame {

    // JDatePicker
    JDatePanelImpl datePanel;
    JDatePickerImpl datePicker;
    JLabel dobFomat;

    /**
     * Creates new form NewJFrame
     */
    public JF_SellReport() {

//        // adding JDatePicker date picker
//        UtilDateModel model = new UtilDateModel();
//        model.setDate(1999, 01, 02);
//        model.setSelected(true);
//        Properties p = new Properties();
//        p.put("text.today", "Today");
//        p.put("text.month", "Month");
//        p.put("text.year", "Year");
//        datePanel = new JDatePanelImpl(model, p);
////        datePicker = new JDatePickerImpl(datePanel, new DateLabelFormatter()); //DateLabelFormatter()
//        dobFomat = new JLabel("(yyyy-mm-dd)");
//        datePicker.setBounds(130, 110, 200, 30);
//        add(datePicker);
        initComponents();
        showFirst();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        closeBtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        usernameTB = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnYear = new javax.swing.JRadioButton();
        btnDay = new javax.swing.JRadioButton();
        btnMonth = new javax.swing.JRadioButton();
        cbYear = new javax.swing.JComboBox<>();
        cbMonth = new javax.swing.JComboBox<>();
        cbDay = new javax.swing.JComboBox<>();
        jPanel23 = new javax.swing.JPanel();
        Customers8 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        billing4 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        BillTable4 = new javax.swing.JTable();
        jPanel25 = new javax.swing.JPanel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        MailNameBD4 = new javax.swing.JTextField();
        AdressBD4 = new javax.swing.JTextField();
        CusNameBD4 = new javax.swing.JTextField();
        GenderBD4 = new javax.swing.JTextField();
        PhoneBD4 = new javax.swing.JTextField();
        jLabel105 = new javax.swing.JLabel();
        CusIDBD4 = new javax.swing.JTextField();
        DisBD4 = new javax.swing.JTextField();
        jLabel106 = new javax.swing.JLabel();
        TypeBD4 = new javax.swing.JTextField();
        Customers9 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        BookIDBD4 = new javax.swing.JTextField();
        AuthorBD4 = new javax.swing.JTextField();
        CateBD4 = new javax.swing.JTextField();
        BookNameBD4 = new javax.swing.JTextField();
        PubBD4 = new javax.swing.JTextField();
        jPanel27 = new javax.swing.JPanel();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        billdetailsTable4 = new javax.swing.JTable();
        totalPaymentBD4 = new javax.swing.JLabel();
        subTotalBD4 = new javax.swing.JLabel();
        discountBD5 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        BIdBD4 = new javax.swing.JTextField();
        BTimeBD4 = new javax.swing.JTextField();
        jLabel117 = new javax.swing.JLabel();
        jLabel118 = new javax.swing.JLabel();
        returnBtn4 = new javax.swing.JButton();
        logoutBtn5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(229, 229, 229));
        jPanel3.setPreferredSize(new java.awt.Dimension(959, 572));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookstore_ms/Images/close-button.png"))); // NOI18N
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(32, 215, 195));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Book Store Software");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookstore_ms/Images/info.png"))); // NOI18N

        usernameTB.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        usernameTB.setForeground(new java.awt.Color(32, 215, 195));
        usernameTB.setText("Username");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameTB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209)
                .addComponent(closeBtn)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(closeBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(usernameTB)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(32, 215, 195));
        jLabel2.setText("Show Report :");

        buttonGroup1.add(btnYear);
        btnYear.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnYear.setSelected(true);
        btnYear.setText("By Year");
        btnYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYearActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnDay);
        btnDay.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnDay.setText("By Day");
        btnDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDayActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnMonth);
        btnMonth.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnMonth.setText("By Month");
        btnMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonthActionPerformed(evt);
            }
        });

        cbMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMonthActionPerformed(evt);
            }
        });

        jPanel23.setBackground(new java.awt.Color(229, 229, 229));
        jPanel23.setForeground(new java.awt.Color(128, 128, 128));
        jPanel23.setPreferredSize(new java.awt.Dimension(1077, 603));

        Customers8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Customers8.setForeground(new java.awt.Color(32, 215, 195));
        Customers8.setText("Customer Information");
        Customers8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Customers8MouseClicked(evt);
            }
        });

        jLabel96.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel96.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookstore_ms/Images/user.png"))); // NOI18N

        billing4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        billing4.setForeground(new java.awt.Color(32, 215, 195));
        billing4.setText("Bill List");
        billing4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billing4MouseClicked(evt);
            }
        });

        jLabel97.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel97.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookstore_ms/Images/billing (1).png"))); // NOI18N

        jLabel98.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel98.setForeground(new java.awt.Color(32, 215, 195));
        jLabel98.setText("Bill Detail");

        jLabel99.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookstore_ms/Images/list_1.png"))); // NOI18N
        jLabel99.setText("jLabel1");

        jPanel24.setBackground(new java.awt.Color(32, 215, 195));
        jPanel24.setPreferredSize(new java.awt.Dimension(55, 3));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BillTable4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BillTable4.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        BillTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CusID", "Price", "Staff", "IsPaid"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        BillTable4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BillTable4.setGridColor(new java.awt.Color(204, 204, 204));
        BillTable4.setName(""); // NOI18N
        BillTable4.setRequestFocusEnabled(false);
        BillTable4.setRowHeight(30);
        BillTable4.setSelectionBackground(new java.awt.Color(32, 215, 195));
        BillTable4.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        BillTable4.setShowGrid(true);
        BillTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BillTable4MouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(BillTable4);

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));
        jPanel25.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel100.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel100.setText("Gender:");
        jPanel25.add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel101.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel101.setText("Email:");
        jPanel25.add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel102.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel102.setText("Phone:");
        jPanel25.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel103.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel103.setText("Name:");
        jPanel25.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 50, 20));

        jLabel104.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel104.setText("Adress:");
        jPanel25.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        MailNameBD4.setEditable(false);
        MailNameBD4.setBackground(new java.awt.Color(255, 255, 255));
        MailNameBD4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        MailNameBD4.setAlignmentX(0.0F);
        MailNameBD4.setAlignmentY(0.0F);
        MailNameBD4.setBorder(null);
        MailNameBD4.setFocusable(false);
        MailNameBD4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        MailNameBD4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MailNameBD4ActionPerformed(evt);
            }
        });
        jPanel25.add(MailNameBD4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 245, 20));

        AdressBD4.setEditable(false);
        AdressBD4.setBackground(new java.awt.Color(255, 255, 255));
        AdressBD4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        AdressBD4.setAlignmentX(0.0F);
        AdressBD4.setAlignmentY(0.0F);
        AdressBD4.setBorder(null);
        AdressBD4.setFocusable(false);
        AdressBD4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        AdressBD4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdressBD4ActionPerformed(evt);
            }
        });
        jPanel25.add(AdressBD4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 236, 20));

        CusNameBD4.setEditable(false);
        CusNameBD4.setBackground(new java.awt.Color(255, 255, 255));
        CusNameBD4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        CusNameBD4.setAlignmentX(0.0F);
        CusNameBD4.setAlignmentY(0.0F);
        CusNameBD4.setBorder(null);
        CusNameBD4.setFocusable(false);
        CusNameBD4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        CusNameBD4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CusNameBD4ActionPerformed(evt);
            }
        });
        jPanel25.add(CusNameBD4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 203, 20));

        GenderBD4.setEditable(false);
        GenderBD4.setBackground(new java.awt.Color(255, 255, 255));
        GenderBD4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        GenderBD4.setAlignmentX(0.0F);
        GenderBD4.setAlignmentY(0.0F);
        GenderBD4.setBorder(null);
        GenderBD4.setFocusable(false);
        GenderBD4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        GenderBD4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderBD4ActionPerformed(evt);
            }
        });
        jPanel25.add(GenderBD4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 173, 20));

        PhoneBD4.setEditable(false);
        PhoneBD4.setBackground(new java.awt.Color(255, 255, 255));
        PhoneBD4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        PhoneBD4.setAlignmentX(0.0F);
        PhoneBD4.setAlignmentY(0.0F);
        PhoneBD4.setBorder(null);
        PhoneBD4.setFocusable(false);
        PhoneBD4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        PhoneBD4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneBD4ActionPerformed(evt);
            }
        });
        jPanel25.add(PhoneBD4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 192, 20));

        jLabel105.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel105.setText("CusID:");
        jPanel25.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        CusIDBD4.setEditable(false);
        CusIDBD4.setBackground(new java.awt.Color(255, 255, 255));
        CusIDBD4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        CusIDBD4.setAlignmentX(0.0F);
        CusIDBD4.setAlignmentY(0.0F);
        CusIDBD4.setBorder(null);
        CusIDBD4.setFocusable(false);
        CusIDBD4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        CusIDBD4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CusIDBD4ActionPerformed(evt);
            }
        });
        jPanel25.add(CusIDBD4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 50, 20));

        DisBD4.setEditable(false);
        DisBD4.setBackground(new java.awt.Color(255, 255, 255));
        DisBD4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        DisBD4.setForeground(new java.awt.Color(255, 255, 255));
        DisBD4.setAlignmentX(0.0F);
        DisBD4.setAlignmentY(0.0F);
        DisBD4.setBorder(null);
        DisBD4.setFocusable(false);
        DisBD4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        DisBD4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisBD4ActionPerformed(evt);
            }
        });
        jPanel25.add(DisBD4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 30, 20));

        jLabel106.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel106.setText("TypeID:");
        jPanel25.add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        TypeBD4.setEditable(false);
        TypeBD4.setBackground(new java.awt.Color(255, 255, 255));
        TypeBD4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        TypeBD4.setAlignmentX(0.0F);
        TypeBD4.setAlignmentY(0.0F);
        TypeBD4.setBorder(null);
        TypeBD4.setFocusable(false);
        TypeBD4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        TypeBD4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeBD4ActionPerformed(evt);
            }
        });
        jPanel25.add(TypeBD4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 30, 20));

        Customers9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Customers9.setForeground(new java.awt.Color(32, 215, 195));
        Customers9.setText("Book Information");
        Customers9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Customers9MouseClicked(evt);
            }
        });

        jLabel107.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel107.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookstore_ms/Images/book.png"))); // NOI18N

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel108.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel108.setText("Book ID:");
        jPanel26.add(jLabel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel109.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel109.setText("Pulisher:");
        jPanel26.add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel110.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel110.setText("Author:");
        jPanel26.add(jLabel110, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel111.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel111.setText("Title:");
        jPanel26.add(jLabel111, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel112.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel112.setText("Category:");
        jPanel26.add(jLabel112, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        BookIDBD4.setEditable(false);
        BookIDBD4.setBackground(new java.awt.Color(255, 255, 255));
        BookIDBD4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        BookIDBD4.setBorder(null);
        BookIDBD4.setFocusable(false);
        BookIDBD4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookIDBD4ActionPerformed(evt);
            }
        });
        jPanel26.add(BookIDBD4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 187, 20));

        AuthorBD4.setEditable(false);
        AuthorBD4.setBackground(new java.awt.Color(255, 255, 255));
        AuthorBD4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        AuthorBD4.setBorder(null);
        AuthorBD4.setFocusable(false);
        AuthorBD4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuthorBD4ActionPerformed(evt);
            }
        });
        jPanel26.add(AuthorBD4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 213, 20));

        CateBD4.setEditable(false);
        CateBD4.setBackground(new java.awt.Color(255, 255, 255));
        CateBD4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        CateBD4.setBorder(null);
        CateBD4.setFocusable(false);
        CateBD4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CateBD4ActionPerformed(evt);
            }
        });
        jPanel26.add(CateBD4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 200, 20));

        BookNameBD4.setEditable(false);
        BookNameBD4.setBackground(new java.awt.Color(255, 255, 255));
        BookNameBD4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        BookNameBD4.setBorder(null);
        BookNameBD4.setFocusable(false);
        BookNameBD4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookNameBD4ActionPerformed(evt);
            }
        });
        jPanel26.add(BookNameBD4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 210, 20));

        PubBD4.setEditable(false);
        PubBD4.setBackground(new java.awt.Color(255, 255, 255));
        PubBD4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        PubBD4.setBorder(null);
        PubBD4.setFocusable(false);
        PubBD4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PubBD4ActionPerformed(evt);
            }
        });
        jPanel26.add(PubBD4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 240, 23));

        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel113.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel113.setText("Subtotal: $");
        jPanel27.add(jLabel113, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        jLabel114.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel114.setText("Discount: - $");
        jPanel27.add(jLabel114, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jLabel115.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel115.setText("Total Payment: $");
        jPanel27.add(jLabel115, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        billdetailsTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Book ID", "Book Name", "Quantity", "Price", "Total Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        billdetailsTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billdetailsTable4MouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(billdetailsTable4);

        jPanel27.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 350, 120));

        totalPaymentBD4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        totalPaymentBD4.setText("xxxxx");
        jPanel27.add(totalPaymentBD4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, -1, -1));

        subTotalBD4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        subTotalBD4.setText("xxxx");
        jPanel27.add(subTotalBD4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, -1));

        discountBD5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        discountBD5.setText("xxxx");
        jPanel27.add(discountBD5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, -1));

        jLabel116.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel116.setText("Details");

        BIdBD4.setBackground(new java.awt.Color(229, 229, 229));
        BIdBD4.setBorder(null);
        BIdBD4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BIdBD4ActionPerformed(evt);
            }
        });

        BTimeBD4.setBackground(new java.awt.Color(229, 229, 229));
        BTimeBD4.setBorder(null);

        jLabel117.setText("ID:");

        jLabel118.setText("Time:");

        returnBtn4.setBackground(new java.awt.Color(229, 229, 229));
        returnBtn4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        returnBtn4.setForeground(new java.awt.Color(32, 215, 195));
        returnBtn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookstore_ms/Images/return.png"))); // NOI18N
        returnBtn4.setText("Return");
        returnBtn4.setToolTipText("");
        returnBtn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnBtn4MouseClicked(evt);
            }
        });
        returnBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtn4ActionPerformed(evt);
            }
        });

        logoutBtn5.setBackground(new java.awt.Color(229, 229, 229));
        logoutBtn5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        logoutBtn5.setForeground(new java.awt.Color(32, 215, 195));
        logoutBtn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookstore_ms/Images/power.png"))); // NOI18N
        logoutBtn5.setText("Logout");
        logoutBtn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtn5MouseClicked(evt);
            }
        });
        logoutBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtn5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, 1113, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addComponent(jLabel96)
                        .addGap(6, 6, 6)
                        .addComponent(Customers8)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel107)
                        .addGap(6, 6, 6)
                        .addComponent(Customers9))
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jLabel116, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel117, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(BIdBD4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel118)
                        .addGap(1, 1, 1)
                        .addComponent(BTimeBD4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(returnBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(870, 870, 870)
                .addComponent(logoutBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel99, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(billing4)
                .addGap(601, 601, 601)
                .addComponent(jLabel97)
                .addGap(6, 6, 6)
                .addComponent(jLabel98))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel99)
                    .addComponent(jLabel97)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(billing4)
                            .addComponent(jLabel98))))
                .addGap(0, 0, 0)
                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel96)
                            .addComponent(Customers8)
                            .addComponent(jLabel107)
                            .addComponent(Customers9))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(jLabel116))
                            .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel117, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BIdBD4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel118, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTimeBD4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(returnBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnYear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMonth)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnYear)
                    .addComponent(btnDay)
                    .addComponent(btnMonth)
                    .addComponent(cbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void btnYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYearActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnYearActionPerformed

    public void showFirst() {

        int[] years = new int[14];
        int startYear = 2010;

        for (int i = 0; i <= 13; i++) {
            years[i] = startYear + i;

        }
        cbYear.removeAllItems();
        for (int year : years) {
            cbYear.addItem(Integer.toString(year));
        }
    }
    private void btnDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDayActionPerformed
        int selectedMonth = Integer.parseInt((String) cbMonth.getSelectedItem());
int selectedYear = Integer.parseInt((String) cbYear.getSelectedItem());
        int daysInMonth;

        if (selectedMonth == 2) {
            // Xử lý tháng 2
            if (selectedYear % 4 == 0) {
                // Năm nhuận
                daysInMonth = 29;
            } else {
                // Năm không nhuận
                daysInMonth = 28;
            }
        } else if (selectedMonth == 4 || selectedMonth == 6 || selectedMonth == 9 || selectedMonth == 11) {
            // Các tháng có 30 ngày
            daysInMonth = 30;
        } else {
            // Các tháng còn lại có 31 ngày
            daysInMonth = 31;
        }

// Tạo danh sách ngày trong tháng và cập nhật combo box
        cbDay.removeAllItems();
        for (int i = 1; i <= daysInMonth; i++) {
            cbDay.addItem(Integer.toString(i));
        }
    }//GEN-LAST:event_btnDayActionPerformed

    private void btnMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonthActionPerformed
        // TODO add your handling code here:
        int[] months = new int[12];
        int startMonth = 1;
        for (int i = 0; i < 12 ;i++)
        {
            months[i] = startMonth + i;
        }
        
        cbMonth.removeAllItems();
        for (int month : months) {
            cbMonth.addItem(Integer.toString(month));
        }
    
    }//GEN-LAST:event_btnMonthActionPerformed

    private void cbMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMonthActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbMonthActionPerformed

    private void Customers8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Customers8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Customers8MouseClicked

    private void billing4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billing4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_billing4MouseClicked

    private void BillTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BillTable4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BillTable4MouseClicked

    private void MailNameBD4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MailNameBD4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MailNameBD4ActionPerformed

    private void AdressBD4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdressBD4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdressBD4ActionPerformed

    private void CusNameBD4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CusNameBD4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CusNameBD4ActionPerformed

    private void GenderBD4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderBD4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderBD4ActionPerformed

    private void PhoneBD4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneBD4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneBD4ActionPerformed

    private void CusIDBD4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CusIDBD4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CusIDBD4ActionPerformed

    private void DisBD4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisBD4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisBD4ActionPerformed

    private void TypeBD4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeBD4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeBD4ActionPerformed

    private void Customers9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Customers9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Customers9MouseClicked

    private void BookIDBD4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookIDBD4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookIDBD4ActionPerformed

    private void AuthorBD4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthorBD4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AuthorBD4ActionPerformed

    private void CateBD4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CateBD4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CateBD4ActionPerformed

    private void BookNameBD4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookNameBD4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookNameBD4ActionPerformed

    private void PubBD4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PubBD4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PubBD4ActionPerformed

    private void billdetailsTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billdetailsTable4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_billdetailsTable4MouseClicked

    private void BIdBD4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BIdBD4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BIdBD4ActionPerformed

    private void returnBtn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnBtn4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_returnBtn4MouseClicked

    private void returnBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnBtn4ActionPerformed

    private void logoutBtn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtn5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutBtn5MouseClicked

    private void logoutBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutBtn5ActionPerformed

//    public class DateLabelFormatter extends AbstractFormatter {
//
//        private String datePattern = "yyyy-MM-dd";
//        private SimpleDateFormat dateFormatter = new SimpleDateFormat(datePattern);
//
//        @Override
//        public Object stringToValue(String text) throws ParseException {
//            return dateFormatter.parseObject(text);
//        }
//
//        @Override
//        public String valueToString(Object value) throws ParseException {
//            if (value != null) {
//                Calendar cal = (Calendar) value;
//                return dateFormatter.format(cal.getTime());
//            }
//            return "";
//        }
//
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_SellReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_SellReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_SellReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_SellReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_SellReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdressBD4;
    private javax.swing.JTextField AuthorBD4;
    private javax.swing.JTextField BIdBD4;
    private javax.swing.JTextField BTimeBD4;
    private javax.swing.JTable BillTable4;
    private javax.swing.JTextField BookIDBD4;
    private javax.swing.JTextField BookNameBD4;
    private javax.swing.JTextField CateBD4;
    private javax.swing.JTextField CusIDBD4;
    private javax.swing.JTextField CusNameBD4;
    private javax.swing.JLabel Customers8;
    private javax.swing.JLabel Customers9;
    private javax.swing.JTextField DisBD4;
    private javax.swing.JTextField GenderBD4;
    private javax.swing.JTextField MailNameBD4;
    private javax.swing.JTextField PhoneBD4;
    private javax.swing.JTextField PubBD4;
    private javax.swing.JTextField TypeBD4;
    private javax.swing.JTable billdetailsTable4;
    private javax.swing.JLabel billing4;
    private javax.swing.JRadioButton btnDay;
    private javax.swing.JRadioButton btnMonth;
    private javax.swing.JRadioButton btnYear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbDay;
    private javax.swing.JComboBox<String> cbMonth;
    private javax.swing.JComboBox<String> cbYear;
    private javax.swing.JLabel closeBtn;
    private javax.swing.JLabel discountBD5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JButton logoutBtn5;
    private javax.swing.JButton returnBtn4;
    private javax.swing.JLabel subTotalBD4;
    private javax.swing.JLabel totalPaymentBD4;
    private javax.swing.JLabel usernameTB;
    // End of variables declaration//GEN-END:variables
}
